# Generated by Django 3.2.6 on 2021-09-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='sub_category',
            field=models.BooleanField(default=False),
        ),
    ]
