# Generated by Django 3.2.6 on 2021-09-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='sub_category',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
