# Generated by Django 3.2.6 on 2021-09-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='stanar-display-placeholder.jpg', null=True, upload_to=''),
        ),
    ]
