# Generated by Django 3.2.6 on 2021-09-18 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('business_name', models.CharField(max_length=100)),
                ('business_phone', models.CharField(max_length=100)),
                ('business_email', models.EmailField(max_length=100)),
                ('business_bio', models.TextField(blank=True)),
                ('instagram_link', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(max_length=100)),
                ('address_line_1', models.CharField(max_length=200)),
                ('address_line_2', models.CharField(blank=True, max_length=200, null=True)),
                ('town', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.CharField(blank=True, default='off', max_length=10, null=True)),
                ('physical', models.CharField(blank=True, default='off', max_length=10, null=True)),
                ('check', models.CharField(blank=True, default='off', max_length=10, null=True)),
                ('paypal', models.CharField(blank=True, default='off', max_length=10, null=True)),
                ('bank_transfer', models.CharField(blank=True, default='off', max_length=10, null=True)),
                ('gift_card', models.CharField(blank=True, default='off', max_length=10, null=True)),
                ('business', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.business')),
            ],
        ),
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_parking', models.CharField(blank=True, default='off', max_length=10, null=True)),
                ('card_accept', models.CharField(blank=True, default='off', max_length=10, null=True)),
                ('disability', models.CharField(blank=True, default='off', max_length=10, null=True)),
                ('child_friendly', models.CharField(blank=True, default='off', max_length=10, null=True)),
                ('pet_friendly', models.CharField(blank=True, default='off', max_length=10, null=True)),
                ('wifi', models.CharField(blank=True, default='off', max_length=10, null=True)),
                ('loyalty_program', models.CharField(blank=True, default='off', max_length=10, null=True)),
                ('business', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.business')),
            ],
        ),
    ]
