# Generated by Django 3.2.6 on 2021-09-24 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('business_name', models.CharField(max_length=100)),
                ('business_phone', models.CharField(max_length=100)),
                ('business_email', models.EmailField(max_length=100)),
                ('business_bio', models.TextField(blank=True)),
                ('instagram_link', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(max_length=100)),
                ('address_line_1', models.CharField(max_length=200)),
                ('address_line_2', models.CharField(blank=True, max_length=200, null=True)),
                ('town', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_hours', models.CharField(blank=True, default='00', max_length=2, null=True)),
                ('duration_mins', models.CharField(blank=True, default='00', max_length=2, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('note', models.TextField(blank=True, max_length=300, null=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.business')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.business')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.service')),
                ('staff', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='stanar-logo-placeholder.jpg', null=True, upload_to='')),
                ('banner', models.ImageField(blank=True, default='stanar-banner-placeholder.jpg', null=True, upload_to='')),
                ('display_1', models.ImageField(blank=True, default='stanar-display-placeholder.jpg', null=True, upload_to='')),
                ('display_2', models.ImageField(blank=True, default='stanar-display-placeholder.jpg', null=True, upload_to='')),
                ('display_3', models.ImageField(blank=True, default='stanar-display-placeholder.jpg', null=True, upload_to='')),
                ('display_4', models.ImageField(blank=True, default='stanar-display-placeholder.jpg', null=True, upload_to='')),
                ('business', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.business')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.CharField(blank=True, default='off', max_length=10, null=True)),
                ('physical', models.CharField(blank=True, default='off', max_length=10, null=True)),
                ('check', models.CharField(blank=True, default='off', max_length=10, null=True)),
                ('paypal', models.CharField(blank=True, default='off', max_length=10, null=True)),
                ('bank_transfer', models.CharField(blank=True, default='off', max_length=10, null=True)),
                ('gift_card', models.CharField(blank=True, default='off', max_length=10, null=True)),
                ('business', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.business')),
            ],
        ),
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_parking', models.CharField(blank=True, default='off', max_length=10, null=True)),
                ('card_accept', models.CharField(blank=True, default='off', max_length=10, null=True)),
                ('disability', models.CharField(blank=True, default='off', max_length=10, null=True)),
                ('child_friendly', models.CharField(blank=True, default='off', max_length=10, null=True)),
                ('pet_friendly', models.CharField(blank=True, default='off', max_length=10, null=True)),
                ('wifi', models.CharField(blank=True, default='off', max_length=10, null=True)),
                ('loyalty_program', models.CharField(blank=True, default='off', max_length=10, null=True)),
                ('business', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.business')),
            ],
        ),
    ]
