# Generated by Django 3.2.6 on 2021-09-18 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.BooleanField(blank=True, default=False, null=True)),
                ('physical', models.BooleanField(blank=True, default=False, null=True)),
                ('check', models.BooleanField(blank=True, default=False, null=True)),
                ('paypal', models.BooleanField(blank=True, default=False, null=True)),
                ('bank_transfer', models.BooleanField(blank=True, default=False, null=True)),
                ('gift_card', models.BooleanField(blank=True, default=False, null=True)),
                ('business', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.business')),
            ],
        ),
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_parking', models.BooleanField(blank=True, default=False, null=True)),
                ('card_accept', models.BooleanField(blank=True, default=False, null=True)),
                ('disability', models.BooleanField(blank=True, default=False, null=True)),
                ('child_friendly', models.BooleanField(blank=True, default=False, null=True)),
                ('pet_friendly', models.BooleanField(blank=True, default=False, null=True)),
                ('wifi', models.BooleanField(blank=True, default=False, null=True)),
                ('loyalty_program', models.BooleanField(blank=True, default=False, null=True)),
                ('business', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.business')),
            ],
        ),
    ]
