# Generated by Django 3.2.6 on 2021-09-20 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='stanar-logo-placeholder.jpg', null=True, upload_to='')),
                ('banner', models.ImageField(blank=True, default='stanar-banner-placeholder.jpg', null=True, upload_to='')),
                ('display_1', models.ImageField(blank=True, default='stanar-display-placeholder.jpg', null=True, upload_to='')),
                ('display_2', models.ImageField(blank=True, default='stanar-display-placeholder.jpg', null=True, upload_to='')),
                ('display_3', models.ImageField(blank=True, default='stanar-display-placeholder.jpg', null=True, upload_to='')),
                ('display_4', models.ImageField(blank=True, default='stanar-display-placeholder.jpg', null=True, upload_to='')),
                ('business', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.business')),
            ],
        ),
    ]
