# Generated by Django 3.2.6 on 2021-09-22 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_sub_category'),
        ('business', '0002_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_hours', models.CharField(max_length=2)),
                ('duration_mins', models.CharField(max_length=2)),
                ('price', models.FloatField(default=0.0)),
                ('note', models.TextField(blank=True, max_length=300, null=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.business')),
                ('service', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
            ],
        ),
    ]
