# Generated by Django 3.2.6 on 2021-09-24 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20210924_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffservice',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.staff'),
        ),
    ]
