# Generated by Django 3.2.6 on 2021-09-22 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_sub_category'),
        ('business', '0003_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
    ]
