# Generated by Django 3.2.6 on 2021-09-24 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_staff_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.business'),
        ),
    ]
