# Generated by Django 3.2.6 on 2021-09-22 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_sub_category'),
        ('business', '0004_alter_service_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration_hours',
            field=models.CharField(blank=True, default='00', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_mins',
            field=models.CharField(blank=True, default='00', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
    ]
